import random
import string
import base64
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
from src.logger_config import Logger

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Username passing logic:
#       In index's hover-show content: front-end get 44-len data (fake token) from local-storage
#    and send it to backend, then the backend get and decode it to the raw msg, then encode it
#    with Crypto and send it back to the front (along with key). Front get the data and decode it
#    with the same logic, then it is the raw username, it can be shown on the page.
#       In register and login page: Front-end get the keys from back and secret the raw username
#    and password string with the AES-128-CBC (Crypto), then pass to backend (along with key), then
#    backend decode them to get the raw string and save raw username to database, the password
#    will be encrypted by bcrypt again to save (or use raw to compare in login process). Then, if
#    it is a login process, the backend will encode raw username info again with xor logic to
#    a 44-len string (fake token) and return it to frontend. The frontend get it and save it to
#    local-storage.
#       Btw, 44-len-data's decode don't need keys, it uses as the token; the Crypto encrypt needs
#    two keys, they must be generated by backend.
#       All functions in this file uses for encode with raw message, to avoid showing them in
#    transmitting procedure. And the font-end owns a same logic for encode and decode.
#
#     * Token generation logics are in utils.py
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


def generate_random_key_for_crypto(length=16):
    """ generate Key & IV """
    chars = string.ascii_letters + string.digits
    return ''.join(random.choice(chars) for _ in range(length))


def encrypt_data(text, key_str, iv_str):
    """ simple encode with data exchange to front-end """
    Logger.info('Encoding data with crypto.')
    key = key_str.encode('utf-8')
    iv = iv_str.encode('utf-8')

    cipher = AES.new(key, AES.MODE_CBC, iv)
    padded_data = pad(text.encode('utf-8'), AES.block_size)
    encrypted_bytes = cipher.encrypt(padded_data)

    return base64.b64encode(encrypted_bytes).decode('utf-8')


def decrypt_data(encrypted_b64, key_str, iv_str):
    """ simple decode with data exchange from front-end """
    Logger.info('Decoding data with crypto.')
    key = key_str.encode('utf-8')
    iv = iv_str.encode('utf-8')

    encrypted_bytes = base64.b64decode(encrypted_b64)
    cipher = AES.new(key, AES.MODE_CBC, iv)

    try:
        decrypted_bytes = unpad(cipher.decrypt(encrypted_bytes), AES.block_size)
        return decrypted_bytes.decode('utf-8')
    except Exception as e:
        Logger.error(f"decode error in crypto: {e}")
        return None
